version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mymoney-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mymoney-test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
