import { AppSidebar } from "@/components/app-sidebar"
import Header from "@/components/header"
import { SidebarProvider } from "@/components/ui/sidebar"
import type { Metadata } from "next"
import "./globals.css"
import { pretendard } from "./fonts/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='ko'
      className={pretendard.variable}
    >
      <body className='font-pretendard antialiased bg-zinc-50'>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <Header />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
