import { AppSidebar } from "@/components/app-sidebar"
import Header from "@/components/header"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import type { Metadata } from "next"
import "./globals.css"
import { pretendard } from "./fonts/fonts"
import { ExchangeRateProvider } from "@/context/ExchangeRateContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='ko'
      className={pretendard.variable}
    >
      <body className='font-pretendard antialiased bg-zinc-50'>
        <ExchangeRateProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="bg-zinc-100">
              <Header />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ExchangeRateProvider>
      </body>
    </html>
  );
}
